package assetcrypt

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite docs/asset-encryption-vectors.json")

// vectorsPath is the conformance file beside the specification; the console's
// node:crypto decryptor and the three client libraries run the same file.
const vectorsPath = "../../../docs/asset-encryption-vectors.json"

// vectorKeyHex is the one non-secret key every test fixture may carry
// (.gitleaks.toml allowlists it by value).
const vectorKeyHex = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

func vectorKey(t *testing.T) Key {
	t.Helper()
	raw, _ := hex.DecodeString(vectorKeyHex)
	k, err := KeyFromBytes(raw)
	if err != nil {
		t.Fatal(err)
	}
	return k
}

// unitLen is the period of the larger plaintexts: the vectors file carries
// one period and the length, and every decryptor rebuilds the plaintext by
// repeating the unit (hex of 130 KB per case would dwarf the file otherwise).
const unitLen = 1024

// unit is a deterministic period of unitLen bytes.
func unit(seed byte) []byte {
	out := make([]byte, unitLen)
	x := uint32(seed) | 0x9e3779b9
	for i := range out {
		x ^= x << 13
		x ^= x >> 17
		x ^= x << 5
		out[i] = byte(x)
	}
	return out
}

// pattern is unit(seed) repeated to n bytes.
func pattern(n int, seed byte) []byte {
	return repeatTo(unit(seed), n)
}

func repeatTo(u []byte, n int) []byte {
	out := make([]byte, n)
	for i := 0; i < n; i += len(u) {
		copy(out[i:], u)
	}
	return out
}

type vectorCase struct {
	Name   string `json:"name"`
	KeyHex string `json:"keyHex"`
	Key    string `json:"key"`
	Path   string `json:"path"`
	// The plaintext is PlaintextUnitHex repeated and cut to PlaintextLength.
	PlaintextUnitHex string `json:"plaintextUnitHex"`
	PlaintextLength  int    `json:"plaintextLength"`
	CiphertextHex    string `json:"ciphertextHex"`
}

func (c vectorCase) plaintext() []byte {
	u, _ := hex.DecodeString(c.PlaintextUnitHex)
	if len(u) == 0 {
		return []byte{}
	}
	return repeatTo(u, c.PlaintextLength)
}

type negativeCase struct {
	Name          string `json:"name"`
	KeyHex        string `json:"keyHex"`
	Key           string `json:"key"`
	Path          string `json:"path"`
	CiphertextHex string `json:"ciphertextHex"`
	Error         string `json:"error"`
}

type vectorFile struct {
	Format   string         `json:"format"`
	Spec     string         `json:"spec"`
	Note     string         `json:"note"`
	Cases    []vectorCase   `json:"cases"`
	Negative []negativeCase `json:"negative"`
}

type positive struct {
	name string
	path string
	unit []byte
	n    int
}

func (p positive) pt() []byte { return repeatTo(p.unit, p.n) }

func positiveCases() []positive {
	hello := []byte("hello, 세계\n")
	return []positive{
		{"empty file", "data/empty.bin", []byte{}, 0},
		{"one byte", "data/one.bin", []byte{0x2a}, 1},
		{"one full first segment (65,464 bytes)", "v3/data/songs.db", unit(1), FirstPlain},
		{"two segments, the last 1 byte (65,465 bytes)", "v3/data/songs.db", unit(2), FirstPlain + 1},
		{"two full segments (130,968 bytes)", "data/two.bin", unit(3), FirstPlain + LaterPlain},
		{"three segments (131,100 bytes)", "v7/music/intro.ogg", unit(4), FirstPlain + LaterPlain + 132},
		{"a non-ASCII path", "v1/데이터/노래.db", hello, len(hello)},
	}
}

func buildVectors(t *testing.T) vectorFile {
	t.Helper()
	k := vectorKey(t)
	f := vectorFile{
		Format: "yyt-enc-v1",
		Spec:   "docs/asset-encryption.md",
		Note:   "Generated by `go test ./internal/assetcrypt -update` in cli/. Every decryptor must accept every case and refuse every negative one with asset_corrupt; the key is the shared non-secret test fixture value.",
	}
	for _, c := range positiveCases() {
		f.Cases = append(f.Cases, vectorCase{
			Name:             c.name,
			KeyHex:           vectorKeyHex,
			Key:              k.String(),
			Path:             c.path,
			PlaintextUnitHex: hex.EncodeToString(c.unit),
			PlaintextLength:  c.n,
			CiphertextHex:    hex.EncodeToString(Encrypt(k, c.path, c.pt())),
		})
	}
	small := Encrypt(k, "data/one.bin", []byte{0x2a})
	two := Encrypt(k, "v3/data/songs.db", pattern(FirstPlain+1, 2))
	flip := func(ct []byte, at int) []byte {
		out := append([]byte(nil), ct...)
		out[at] ^= 0x01
		return out
	}
	swapped := append([]byte(nil), two[:HeaderLen]...)
	swapped = append(swapped, two[SegmentSize:]...)
	swapped = append(swapped, two[HeaderLen:SegmentSize]...)
	otherKey, _ := KeyFromBytes(bytes.Repeat([]byte{0xfe, 0xdc, 0xba, 0x98}, 8))
	neg := []struct {
		name string
		key  Key
		path string
		ct   []byte
	}{
		{"a flipped tag byte", k, "data/one.bin", flip(small, len(small)-1)},
		{"a flipped ciphertext byte", k, "data/one.bin", flip(small, HeaderLen)},
		{"truncated by one segment", k, "v3/data/songs.db", two[:SegmentSize]},
		{"truncated inside the last segment", k, "v3/data/songs.db", two[:len(two)-1]},
		{"appended bytes", k, "data/one.bin", append(append([]byte(nil), small...), 0x00)},
		{"two segments swapped", k, "v3/data/songs.db", swapped},
		{"the wrong path", k, "data/other.bin", small},
		// The case's key is the vector key; the bytes were made under another
		// one, so the file never carries a second key text.
		{"the wrong key", k, "data/one.bin", Encrypt(otherKey, "data/one.bin", []byte{0x2a})},
		{"a header length byte other than 0x28", k, "data/one.bin", flip(small, 0)},
	}
	for _, n := range neg {
		f.Negative = append(f.Negative, negativeCase{
			Name:          n.name,
			KeyHex:        hex.EncodeToString(n.key.Bytes()),
			Key:           n.key.String(),
			Path:          n.path,
			CiphertextHex: hex.EncodeToString(n.ct),
			Error:         "asset_corrupt",
		})
	}
	return f
}

func TestVectorsMatchTheDocsFile(t *testing.T) {
	want := buildVectors(t)
	b, err := json.MarshalIndent(want, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	b = append(b, '\n')
	p := filepath.Clean(vectorsPath)
	if *update {
		if err := os.WriteFile(p, b, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	have, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("%v (run with -update to write it)", err)
	}
	if !bytes.Equal(have, b) {
		t.Fatalf("%s differs from what this implementation produces; run `go test ./internal/assetcrypt -update` if the change is intended", p)
	}
	// And the file, read back, decrypts and refuses as it says.
	var f vectorFile
	if err := json.Unmarshal(have, &f); err != nil {
		t.Fatal(err)
	}
	for _, c := range f.Cases {
		k, err := ParseKey(c.Key)
		if err != nil {
			t.Fatal(c.Name, err)
		}
		ct, _ := hex.DecodeString(c.CiphertextHex)
		pt := c.plaintext()
		got, err := Decrypt(k, c.Path, ct)
		if err != nil || !bytes.Equal(got, pt) {
			t.Errorf("%s: decrypt: %v", c.Name, err)
		}
	}
	for _, n := range f.Negative {
		k, _ := ParseKey(n.Key)
		ct, _ := hex.DecodeString(n.CiphertextHex)
		if _, err := Decrypt(k, n.Path, ct); !errors.Is(err, ErrCorrupt) {
			t.Errorf("%s: want asset_corrupt, got %v", n.Name, err)
		}
	}
}

func TestParseKey(t *testing.T) {
	k := vectorKey(t)
	text := k.String()
	if len(text) != len(KeyPrefix)+43 || !strings.HasPrefix(text, KeyPrefix) {
		t.Fatalf("text form %q", text)
	}
	back, err := ParseKey(text)
	if err != nil || back != k {
		t.Fatalf("round trip: %v", err)
	}
	bad := []string{
		"",
		text[:len(text)-1],
		text + "A",
		"yak2." + text[5:],
		"YAK1." + text[5:],
		text[:len(text)-1] + "B", // not canonical: the last character encodes 2 bits only
		text[:len(text)-1] + "=",
		KeyPrefix + strings.Repeat("_", 43), // 0xff bytes, but the last character is not canonical
		KeyPrefix + strings.Repeat("/", 43),
		text[:20] + " " + text[21:],
	}
	for _, b := range bad {
		if _, err := ParseKey(b); !errors.Is(err, ErrBadKey) {
			t.Errorf("%q: want bad_key, got %v", b, err)
		}
	}
	// A canonical last character round-trips even when it is one of the
	// sixteen allowed ones.
	for _, c := range "AEIMQUYcgkosw048" {
		if _, err := ParseKey(text[:len(text)-1] + string(c)); err != nil {
			t.Errorf("last char %c: %v", c, err)
		}
	}
	if _, err := KeyFromBytes(make([]byte, 31)); !errors.Is(err, ErrBadKey) {
		t.Error("31 bytes accepted")
	}
}

func TestSegmentMath(t *testing.T) {
	cases := []struct{ plain, segments, cipher int64 }{
		{0, 1, 72},
		{1, 1, 73},
		{FirstPlain, 1, SegmentSize},
		{FirstPlain + 1, 2, SegmentSize + 33},
		{FirstPlain + LaterPlain, 2, 2 * SegmentSize},
		{FirstPlain + LaterPlain + 1, 3, 2*SegmentSize + 33},
		{MaxPlaintext, 4099, MaxCiphertext},
	}
	for _, c := range cases {
		if SegmentCount(c.plain) != c.segments || CiphertextLen(c.plain) != c.cipher {
			t.Errorf("plain %d: got %d segments, %d bytes", c.plain, SegmentCount(c.plain), CiphertextLen(c.plain))
		}
		n, err := segmentsOf(c.cipher)
		if err != nil || n != c.segments {
			t.Errorf("cipher %d: got %d segments, %v", c.cipher, n, err)
		}
	}
	for _, bad := range []int64{0, 71, SegmentSize + 1, SegmentSize + 32, 2*SegmentSize + 32, MaxCiphertext + 1} {
		if _, err := segmentsOf(bad); !errors.Is(err, ErrCorrupt) {
			t.Errorf("cipher %d accepted", bad)
		}
	}
	if SegmentOf(FirstPlain-1) != 0 || SegmentOf(FirstPlain) != 1 || SegmentOf(FirstPlain+LaterPlain-1) != 1 || SegmentOf(FirstPlain+LaterPlain) != 2 {
		t.Error("SegmentOf")
	}
	if PStart(0) != 0 || PStart(1) != FirstPlain || PStart(2) != FirstPlain+LaterPlain || CStart(0) != HeaderLen || CStart(3) != 3*SegmentSize {
		t.Error("starts")
	}
}

func TestDeterministicAndDistinct(t *testing.T) {
	k := vectorKey(t)
	a := Encrypt(k, "p", []byte("same"))
	if !bytes.Equal(a, Encrypt(k, "p", []byte("same"))) {
		t.Fatal("same input, different bytes")
	}
	// Two plaintexts under one AD never share a header (no keystream reuse).
	b := Encrypt(k, "p", []byte("samf"))
	if bytes.Equal(a[:HeaderLen], b[:HeaderLen]) {
		t.Fatal("different plaintexts share a header")
	}
	c := Encrypt(k, "q", []byte("same"))
	if bytes.Equal(a[:HeaderLen], c[:HeaderLen]) {
		t.Fatal("different paths share a header")
	}
	other, _ := KeyFromBytes(bytes.Repeat([]byte{1}, 32))
	if bytes.Equal(a[:HeaderLen], Encrypt(other, "p", []byte("same"))[:HeaderLen]) {
		t.Fatal("different keys share a header")
	}
}

type reopen struct {
	contents [][]byte
	calls    int
}

func (r *reopen) open() (io.ReadCloser, error) {
	c := r.contents[min(r.calls, len(r.contents)-1)]
	r.calls++
	return io.NopCloser(bytes.NewReader(c)), nil
}

func TestEncryptStream(t *testing.T) {
	k := vectorKey(t)
	for _, c := range positiveCases() {
		var out bytes.Buffer
		n, sha, err := EncryptStream(k, c.path, (&reopen{contents: [][]byte{c.pt()}}).open, &out)
		if err != nil || n != int64(c.n) {
			t.Fatalf("%s: %v", c.name, err)
		}
		if want := Encrypt(k, c.path, c.pt()); !bytes.Equal(out.Bytes(), want) {
			t.Fatalf("%s: stream and memory differ", c.name)
		}
		if sha != sha256.Sum256(out.Bytes()) {
			t.Fatalf("%s: sha", c.name)
		}
	}
	// The second pass reads other bytes: same length, longer, shorter.
	base := pattern(FirstPlain+10, 9)
	changed := append([]byte(nil), base...)
	changed[FirstPlain+5] ^= 0xff
	for name, second := range map[string][]byte{
		"same length": changed,
		"longer":      append(append([]byte(nil), base...), 1),
		"shorter":     base[:len(base)-1],
	} {
		var out bytes.Buffer
		_, _, err := EncryptStream(k, "p", (&reopen{contents: [][]byte{base, second}}).open, &out)
		if !errors.Is(err, ErrChanged) {
			t.Errorf("%s: want ErrChanged, got %v", name, err)
		}
	}
}

func TestDecryptStreamAndRanges(t *testing.T) {
	k := vectorKey(t)
	pt := pattern(200_000, 4)
	ct := Encrypt(k, "v7/music/intro.ogg", pt)
	var out bytes.Buffer
	if err := DecryptStream(k, "v7/music/intro.ogg", int64(len(ct)), bytes.NewReader(ct), &out); err != nil || !bytes.Equal(out.Bytes(), pt) {
		t.Fatalf("stream: %v", err)
	}
	if err := DecryptStream(k, "v7/music/intro.ogg", int64(len(ct)), bytes.NewReader(ct[:len(ct)-1]), io.Discard); !errors.Is(err, ErrCorrupt) {
		t.Fatalf("short stream: %v", err)
	}
	if err := DecryptStream(k, "v7/music/intro.ogg", int64(len(ct)), bytes.NewReader(append(append([]byte(nil), ct...), 0)), io.Discard); !errors.Is(err, ErrCorrupt) {
		t.Fatalf("long stream: %v", err)
	}
	d, err := NewDecryptor(k, "v7/music/intro.ogg", ct[:HeaderLen], int64(len(ct)))
	if err != nil {
		t.Fatal(err)
	}
	if d.Segments != 4 || d.PlaintextLen() != 200_000 {
		t.Fatalf("segments %d plain %d", d.Segments, d.PlaintextLen())
	}
	// A plaintext range [a, b) maps onto whole segments, fetched and verified
	// one at a time, then sliced.
	a, b := int64(FirstPlain-3), int64(FirstPlain+LaterPlain+7)
	var got []byte
	for i := SegmentOf(a); i <= SegmentOf(b-1); i++ {
		s, e := d.Extent(i)
		p, err := d.Open(i, ct[s:e])
		if err != nil {
			t.Fatal(err)
		}
		got = append(got, p...)
	}
	off := a - PStart(SegmentOf(a))
	if !bytes.Equal(got[off:off+(b-a)], pt[a:b]) {
		t.Fatal("range slice")
	}
	// A segment opened under the wrong index or with a byte off fails.
	s, e := d.Extent(1)
	if _, err := d.Open(2, ct[s:e]); !errors.Is(err, ErrCorrupt) {
		t.Error("wrong index accepted")
	}
	if _, err := d.Open(1, ct[s:e-1]); !errors.Is(err, ErrCorrupt) {
		t.Error("short segment accepted")
	}
	if _, err := d.Open(4, nil); !errors.Is(err, ErrCorrupt) {
		t.Error("segment past the end accepted")
	}
}
